### ISSUE TITLE
problem with "logical OR" or problem in my mind, lol?

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/micromatch#11]
I use makeRe to generate regex based on glob pattern to test against some filepath.

examples
```js
var expected = false;
var options = {};
var pattern = 'maiden/{**/*.,*.}';
var re = mm.makeRe(pattern, options);
console.log(re.test('maiden/code'));
//=> true
```
isMatch()
```js
var expected = false;
var options = {};
var pattern = 'maiden/{**/*.,*.}';
var match = mm.isMatch('maiden/code', pattern, options);
console.log(match);
//=> true
```
micromatch()
```js
var expected = [];
var options = {};
var pattern = 'maiden/{**/*.,*.}';
var match = mm('maiden/code', pattern, options);
console.log(match);
//=> ['maiden/code']
```
I think its logical to return `true` only if there no dots in the pattern, ie `'maiden/{**/*,*}'`

**Comment by tunnckoCore** [comment]
Just dont want to match folder names, this is the idea.

**Comment by jonschlinkert** [comment]
it's a bug. also, for reference (and reminder to me) this is what bash returns for your pattern:

```bash
maiden/**/*. maiden/*.
```

**Comment by tunnckoCore** [comment]
Cool, okey, I'll wait then :)

I just workin on glob stream idea.

**Comment by tunnckoCore** [comment]
examples updated

**Comment by jonschlinkert** [comment]
should be good. let me know if you have any more problems.

**Comment by tunnckoCore** [comment]
Awesome, works! Very fast response.

**Comment by tunnckoCore** [comment]
@jonschlinkert hmmm, strange
why this not works? Is related to this fix?

```js
var expected = false;
var options = {};
var pattern = 'maiden/**/*.*'; //also 
var match = mm.isMatch('maiden/code/abc.js', pattern, options);
console.log(match);
//=> false
```

**Comment by jonschlinkert** [comment]
yeah I see exactly why that's happening. I'll get it fixed. sorry

**Comment by jonschlinkert** [comment]
done. looks like I broke the last one you posted in a recent optimization.

**Comment by tunnckoCore** [comment]
Yeyy! Good job.

**Comment by jonschlinkert** [comment]
all working for you now?

**Comment by tunnckoCore** [comment]
Yep.

**Comment by jonschlinkert** [comment]
:+1:
