### ISSUE TITLE
make patterns the first arg?

### ISSUE THREAD

**Issue by jonschlinkert** [jonschlinkert/micromatch#12]
This is a major breaking change, and it's probably a bad idea given that minimatch has gotten everyone used to passing patterns as the second arg, but I've always strongly disliked it and found it confusing. 

I'm curious if anyone else agrees with this. 

This is the current signature, with pattern(s) usually the second arg:

```js
mm(['a/b/a.md', 'a/b/b.md', 'a/b/c.md', 'a/b/d.md', ], '**/*.md');
```

I think it makes more sense like this:

```js
mm('**/*.md', ['a/b/a.md', 'a/b/b.md', 'a/b/c.md', 'a/b/d.md']);
```

This signature makes using the lib more consistent when arguments are partially applied to create matching functions, like `var isMatch = matcher('foo/*.md');` which returns a function that could be passed to `Array#filter` for example. 

Also, passing the pattern first feels more natural when regex is used instead of a glob pattern. 

```js
mm(/\.md$/, ['a/b/a.md', 'a/b/b.md', 'a/b/c.md', 'a/b/d.md']);
```

**Comment by tunnckoCore** [comment]
:+1:

**Comment by es128** [comment]
:+1: for the primary API, but you should continue to provide methods that accomplish drop-in equivalency with matching signatures such as `mm.multimatch(array, pattern)` and `mm.minimatch(string, glob)`

**Comment by jonschlinkert** [comment]
Hmm, interesting. So actually add methods to provide parity? like a "minimatch" mode or "multimatch" mode?

**Comment by es128** [comment]
Yeah, well at least just for the main functions. I think it would help people migrate, you'd just drop `micromatch.` in front of the existing `minimatch` calls.

**Comment by tunnckoCore** [comment]
Hm yea, interesting idea, but if someone is going to add `micromatch` in front of `minimatch/multimatch` its better to replace them with `micromatch.isMatch()` or/and `mm() constructor`.

Jon, one idea from yesterday - micromatch.base(string/array) - for getting the base path of glob(s), like base in `.expand().tokens.base`. Use case - I dont want to use whole expand to only get the base and dont want to require one more dependency - `glob-base`.

**Comment by es128** [comment]
> better to replace them directly with micromatch.isMatch() or/and mm() constructor

But now if this change is implemented they'll also have to change arg order. And maybe there will be other differences in the future. The thought behind my suggestion is reducing friction for adoption of this lib as a replacement for those well-established alternatives. The further micromatch deviates from what people are used to, the more friction there will be.

**Comment by jonschlinkert** [comment]
> The further micromatch deviates from what people are used to, the more friction there will be.

Agreed, for this reason I think this is a bad idea. For my own tastes that's kind of a bummer, but it is what it is... closing

**Comment by es128** [comment]
Anyone preferring the other order does already have the option of doing `mm.matcher(pattern)(path)`, which is reasonably close.

**Comment by jonschlinkert** [comment]
true. and really, if I cared about it so much for my own projects I guess I could wrap it in a function and revers the args lol.

**Comment by es128** [comment]
I did pretty much the same thing here https://github.com/es128/progeny/commit/9706276b4c36c0e05de1b68de54ac3e3609785c1 when I decided I needed args reversed to improve future cases but still needed to maintain compatibility with the original consumer.

**Comment by jonschlinkert** [comment]
great minds think alike! except mine thought it like 6 months later... takes me a while sometimes
