### ISSUE TITLE
problem with re-include, excluded path

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/micromatch#13]
Because I still working on glob-fs idea :D lol
Actually it works on 80% of the common usage of gulp/glob-stream, fails only on complex fixtures, or no logical tests (look at you glob-stream, nah.. it have very very weird tests).
Btw, talking about that, can you answer me why is needed [to ignore negate glob if it is first in given patterns](https://github.com/wearefractal/glob-stream/blob/master/test/main.js#L441-L457)?!
No logic for me... nor of matching libs (micromatch/minimatch/node-glob) have this behaving.. lol.

### On topic
```js
var micromatch = require('micromatch')
var multimatch = require('multimatch')

var paths = [
  'foo/',
  'foo/bar.js',
  'foo/bar.md',
  'foo/bar.txt',
  'foo/bar.hbs',
  'foo/bar.json',
  'foo/bar.coffee',
  'foo/bar/',
  'foo/bar/bar.js',
  'foo/bar/bar.md',
  'foo/bar/bar.txt',
  'foo/bar/bar.hbs',
  'foo/bar/bar.json',
  'foo/bar/bar.coffee',
];

var patterns = [
  'foo/**',
  '!foo/',
  '!foo/bar/',
  '!foo/bar/*.{j*,txt,hbs}',
  'foo/bar/*.json',
];

var res = micromatch(paths, patterns);

console.log(res, res.length);

```
**micromatch**, note there `foo/bar/bar.json` missing
```
[ 'foo/bar.js',
  'foo/bar.md',
  'foo/bar.txt',
  'foo/bar.hbs',
  'foo/bar.json',
  'foo/bar.coffee',
  'foo/bar/bar.md',
  'foo/bar/bar.coffee' ] 8
```
**multimatch**, all is okey
```
[ 'foo/bar.js',
  'foo/bar.md',
  'foo/bar.txt',
  'foo/bar.hbs',
  'foo/bar.json',
  'foo/bar.coffee',
  'foo/bar/bar.md',
  'foo/bar/bar.coffee',
  'foo/bar/bar.json' ] 9
```

**Comment by tunnckoCore** [comment]
or say we have this one
```js
var patterns = [
  'foo/**',               // include all filepaths (files and folders)
  '!foo/',                // we dont want `foo/` in the list
  '!foo/bar/',            // and also dont want `foo/bar/`
  '!foo/bar/*',           // we dont want all files
  'foo/bar/*.j*',         // except that are .js and .json
];
```

**Comment by jonschlinkert** [comment]
> note there foo/bar/bar.json missing

This is exactly what I was talking about with "re-inclusion" patterns. You said: https://github.com/jonschlinkert/glob-fs/issues/1#issuecomment-68498242. 

Now you know what I mean? This isn't a bug, I did the PR to multimatch that allows it to re-include patterns like that, I can do the same here. IMO, this is the expected result since you are removing it from the set. But maybe it makes more sense to re-include.

> talking about that, can you answer me why is needed to ignore negate glob if it is first in given patterns?!

I have no idea, I agree. it makes no sense

**Comment by jonschlinkert** [comment]
Initially I was thinking maybe we should change to what multimatch does, but I'm not sure that's correct.  You can get the exact result you want with `foo/bar/*.j*`, right? Why exclude everything first, then include that?

**Comment by jonschlinkert** [comment]
also I'm almost ready to push up a first pass at glob-fs. I focused 100% on the correctness of resolving paths, so it's all sync atm. It will be easy to do async, promises, streams whatever once the basic path logic is down

**Comment by tunnckoCore** [comment]
Hmm, right, clear. Yea, maybe make more sense to save this behaving and allow users to un-negate patterns in options, like not-documented `ignore` option.

> You can get the exact result you want with foo/bar/*.j*, right?

Yep, but testing, complexity, possible use cases and etc.

> also I'm almost ready to push up a first pass at glob-fs.

Great! From you sync, from me streams, haha. Almost pass all gulp/glob-stream tests. lol
Benchmarks shows x22,000 faster than glob-stream and its normal. :) glob-stream is slowest thing that I ever seen, srsly. And tools from this chain glob-stream -> vinyl-fs -> gulp, verb, template, assemble are very slow natively, because the glob-stream and glob + minimatch.

But yea, you know that - for this reason we work on micromatch/glob-fs :)

**Comment by tunnckoCore** [comment]
> actually, I think the reason they did that is because they didn't have the correct logic to do inclusion/exclusion patterns, like what was implemented in multimatch and globby

mm, yea and for this reason we'll never pass 90-100% of gulp/glob-stream/vinyl-fs tests and they are very very weird and low quality. They not deserves 100%-coverage-badge LOL

**Comment by jonschlinkert** [comment]
@tunnckoCore was this resolved?

**Comment by tunnckoCore** [comment]
I'll look after 10-20mins

**Comment by jonschlinkert** [comment]
no prob, I don't know how long I'll last anyway, trying to keep my eyes open!

**Comment by tunnckoCore** [comment]
@jonschlinkert okey, we can close and wait your push.

**Comment by jonschlinkert** [comment]
k thx
