### ISSUE TITLE
Bug with partial wildcards

### ISSUE THREAD

**Issue by es128** [jonschlinkert/micromatch#15]
```
> mm.isMatch('../test-fixtures/add.txt', '../test-fixtures/**/a*.txt')
true
> mm.isMatch('../test-fixtures/add.txt', '../test-*/**/a*.txt')
false
> mm.isMatch('../test-fixtures/subdir/subsub/a.txt', '../test-*/**/a*.txt')
false
> mm.isMatch('../test-fixtures/subdir/subsub/ab.txt', '../test-*/**/a*.txt')
true
```

Realized this is the cause of a few newly failing tests in chokidar

**Comment by es128** [comment]
Looks like it's specific to the globstar occurring right after the partial (tailing) wildard - the `*/**` part.

```
> mm.makeRe('../test-*/**/a*.txt')
/^(?:..\/test-(?!\.)(?=.)[^\/]*?\/.*\/a(?!\.)(?=.)[^\/]*?\.txt)$/
> mm.makeRe('../test-fixtures/**/a*.txt')
/^(?:(?:..\/test-fixtures\/a(?!\.)(?=.)[^\/]*?\.txt|..\/test-fixtures\/.*\/a(?!\.)(?=.)[^\/]*?\.txt))$/
> mm.makeRe('../test-*tures/**/a*.txt')
/^(?:(?:..\/test-(?!\.)(?=.)[^\/]*?tures\/a(?!\.)(?=.)[^\/]*?\.txt|..\/test-(?!\.)(?=.)[^\/]*?tures\/.*\/a(?!\.)(?=.)[^\/]*?\.txt))$/
> mm.isMatch('../test-fixtures/add.txt', '../test-*/**/a*.txt')
false
> mm.isMatch('../test-fixtures/add.txt', '../test-*tures/**/a*.txt')
true
```

**Comment by es128** [comment]
Been digging into this. Focusing on this line atm https://github.com/jonschlinkert/micromatch/blob/c007899ae1e288310cc0c43d5d57faf6d7ec671a/lib/expand.js#L138

Appears to be where the globstar handling fails, probably because of the `\w`

**Comment by es128** [comment]
Ok it's actually the `\w`s down in https://github.com/jonschlinkert/micromatch/blob/c007899ae1e288310cc0c43d5d57faf6d7ec671a/lib/expand.js#L284-L294

Replacing them with `[^\/]` fixes the issue. Now to try it against the rest of the test suite and write a new test...

**Comment by es128** [comment]
The fix described in the last comment did not fully fix the issue. There seems to be a secondary problem with partial wildcard matches after a globstar as well.

```
> mm.isMatch('a/b.txt', '**/*.txt')
true
> mm.isMatch('a/b.txt', '**/b.txt')
true
> mm.isMatch('a/b.txt', '**/b*.txt')
false
> mm.isMatch('a/bc.txt', '**/b*.txt')
true
```

**Comment by jonschlinkert** [comment]
sorry I've been offline all day. just reading over this now

**Comment by es128** [comment]
Was just beginning to prepare a branch and PR

**Comment by jonschlinkert** [comment]
did you figure out which regex was causing it?

**Comment by jonschlinkert** [comment]
crazy that this pattern wouldn't be anywhere in the unit tests...

**Comment by es128** [comment]
I have figured out half of the issue so far - with the `optionalGlobstar` function. Although it points to an assumption that may need to be adjusted elsewhere too regarding using `\w` to indicate path part boundaries

**Comment by jonschlinkert** [comment]
Ok, I can get it the rest of the way. Do you want to do the pr still?

**Comment by jonschlinkert** [comment]
Sorry you had to deal with this.

**Comment by es128** [comment]
Yeah I'll get the PR started in a minute, but on a branch here so you'll be able to keep pushing commits to it and finish up.

> Sorry you had to deal with this

No worries. It was an opportunity to get acquainted with how this thing works

**Comment by jonschlinkert** [comment]
ah, wait, this is the one that's causing the issue, right?

```
> mm.isMatch('a/b.txt', '**/b*.txt')
false
```

If so, I can fix that, but it was intentional, since that's how the specification is written, but it's not how minimatch works. I like how minimatch works for this - so we can change it

**Comment by jonschlinkert** [comment]
> Yeah I'll get the PR started in a minute, but on a branch here so you'll be able to keep pushing commits to it and finish up.

great, thanks!

**Comment by jonschlinkert** [comment]
I'm looking for that spec, it was either wildmatch (used by git) or bash. no matter though since we're changing it

**Comment by es128** [comment]
That's the part I hadn't solved yet.

This is a separate problem as well (which I have solved)

```
mm.isMatch('a/b-c/z.js', 'a/b-*/**/z.js')
```

**Comment by jonschlinkert** [comment]
ok, great.

**Comment by jonschlinkert** [comment]
@es128 would you mind pushing up some failing unit tests that describe all the failing patterns? Maybe just create a section [right here](https://github.com/jonschlinkert/micromatch/blob/fix-15/test/match.js#L74) and name it something like `issue #15`?

**Comment by jonschlinkert** [comment]
ha, well you might have already done it. and that's a better place too probably

**Comment by es128** [comment]
Yeah I tried to isolate them to expose the observed issues (and potential related ones).

But I was mainly focusing on the use case that I started with - I suspect there are more holes that can be poked. Would take a close look at any regex that uses `\w`

**Comment by jonschlinkert** [comment]
looks like they're all they same issue.  

> Would take a close look at any regex that uses \w

If it makes sense to change all boundaries to use slashes instead of word characters. I'll try to get this one fixed then we can go from there and decide where else we want to depart from spec

**Comment by jonschlinkert** [comment]
btw, one thing that might not be immediately obvious in `expand.js` is how I'm using `glob.repl` versus `replace`. they're they same except `replace` also does escaping on the patterns so we don't continue to replace `?` and `*` characters throughout parsing

**Comment by es128** [comment]
That did confuse me briefly when I was monitoring the value of `pattern` instead of `glob.pattern`

**Comment by jonschlinkert** [comment]
quick glance, there are only four places using `\w`. 

- one is for drive letters `\w:`
- two are dotfile related

but the other we might be able to get rid of

**Comment by jonschlinkert** [comment]
did you notice the `track` option?

**Comment by jonschlinkert** [comment]
it might not be documented...

**Comment by es128** [comment]
Sorry AFK at this point. But no, didn't notice it

**Comment by jonschlinkert** [comment]
no prob. I'm on it

**Comment by jonschlinkert** [comment]
I have a fix. I'll be pushing it up in a bit after testing more

**Comment by jonschlinkert** [comment]
I'm still working on the fix. It's not the regex or getting to work that's a problem, it's the spec and inconsistencies with minimatch (or rather, minimatch's inconsistencies), and I want to make sure I'm not missing something before I push this up.  In the meantime, I pushed up a patch with your fix.

**Comment by jonschlinkert** [comment]
meant to just comment....

**Comment by es128** [comment]
Alright. The publish wasn't necessary - the patch I had committed wasn't enough to make the chokidar tests pass. But no worries, looking forward to your the fixes you're polishing up.

**Comment by jonschlinkert** [comment]
k, thx. just wanted to show this, here is one of the many examples of inconsistencies with minimatch:

```js
var minimatch = require('minimatch');
console.log(minimatch('foo/baz/bar', 'foo/**/**/bar'))
//=> true
console.log(minimatch.makeRe('foo/**/**/bar').test('foo/baz/bar'))
//=> false
```

This, and gaps in the spec, are what made this a pita in the beginning

**Comment by jonschlinkert** [comment]
for the heck of it, here's another one for you. Run the following:

```js
var minimatch = require('minimatch');
var micromatch = require('./');


console.log('micromatch:')
console.log(micromatch.makeRe('**/z*.js'))
console.log(micromatch.isMatch('z.js', '**/z*.js'))
console.log(micromatch.makeRe('**/z*.js').test('z.js'))

console.log()
console.log('----------')
console.log()

console.log('minimatch:')
console.log(minimatch.makeRe('**/z*.js'))
console.log(minimatch('z.js', '**/z*.js'))
console.log(minimatch.makeRe('**/z*.js').test('z.js'))
```

Outputs:

```
micromatch:
/^(?:(^|.+\/)(?=.)z[^/]*?\.js)$/
true
true

----------

minimatch:
/^(?:(?:(?!(?:\/|^)\.).)*?\/(?=.)z[^/]*?\.js)$/
true
false
```

**Comment by tunnckoCore** [comment]
> console.log(micromatch.makeRe('**/z*.js').test('z.js'))

damn, this is dramatically bad.

**Comment by jonschlinkert** [comment]
good grief, please lighten up the tone a little. that doesn't help. Try posting a proposed solution instead to encourage discussion and collaboration to solve the problem. 

None of these patterns is too difficult to implement. of course we'll have some things that didn't get tested:
 - including some seemingly obvious ones at first.  but at the end of the day:
- we would have to make 150 patches like the one we did this past week for normalizing file paths to make micromatch as slow as minimatch. 
- the code here isn't perfect (yet) but it passes more tests than minimatch
- the code is far more maintainable than minimatch, lending itself to be more reliable over the long run

why focus on a snippet of code?

**Comment by es128** [comment]
The code in [the quote](https://github.com/jonschlinkert/micromatch/issues/15#issuecomment-87502241) is modified from what was posted earlier in the thread. That version evaluates as `false`, which makes sense. The original version started with a globstar, and it evaluates as `true` (`console.log(micromatch.makeRe('**/z*.js').test('z.js'))`). Both cases currently behave exactly as I'd expect them to.

**Comment by jonschlinkert** [comment]
yeah I was just going to say, I just tested it and the code produces what I would expect:

```js
console.log(micromatch.makeRe('*/z.js').test('z.js'))
//=> false
```

@tunnckoCore is there a reason that should evaluate to `true`?

**Comment by tunnckoCore** [comment]
> is there a reason that should evaluate to true?

no, exactly what I mean. it should stay false.

**Comment by tunnckoCore** [comment]
there's no logic to be `true` and also here
```js
 mm.isMatch('a/b-c/z.js', 'a/b-*/**/z.js').should.be.true;
```

**Comment by jonschlinkert** [comment]
that result is correct. `/**/` may also be evaluated as `/`

**Comment by jonschlinkert** [comment]
and `/**/**/**/**/**/**/**/**/**/**/**/**/**/**` may also be evaluate as `/`

**Comment by jonschlinkert** [comment]
@tunnckoCore is it possible that you misread the example above where **minimatch** fails, thinking it was this library?

**Comment by tunnckoCore** [comment]
[this one](https://github.com/jonschlinkert/micromatch/issues/15#issuecomment-86789730)? no.

idk, sorry for the tone around, but Im just not okey with the [added tests](https://github.com/jonschlinkert/micromatch/commit/2409bae7338d09ebf64d0b51476c643457c4ee73) and think that they should be false.

**Comment by tunnckoCore** [comment]
okey if we [back to this comment](https://github.com/jonschlinkert/micromatch/issues/15#issuecomment-86698744) I understand that the problem was that this one
```
> mm.isMatch('a/b.txt', '**/b*.txt')
false
```
returns false?

**Comment by es128** [comment]
Seems like you simply disagree with how globstar is meant to work. 

Except [this one](https://github.com/jonschlinkert/micromatch/commit/2409bae7338d09ebf64d0b51476c643457c4ee73#diff-0695d9db3c89e5879a8ab1497522e46eR73) already existed before and you didn't take issue with it. 

The glob spec and minimatch both also agree that globstar means 0 or more subdirs, not 1 or more

**Comment by tunnckoCore** [comment]
> Except this one already existed before and you didn't take issue with it.

yea I notice that.

**Comment by jonschlinkert** [comment]
the only one that looks wrong to me is `console.log(micromatch.isMatch('z.js', '**/z*.js'));` I can't see how that would be correct.

**Comment by es128** [comment]
That's right. 

```js
mm.isMatch('a/b.txt', '**/b*.txt')
```
should be true.

**Comment by jonschlinkert** [comment]
but that's different since the path to match against has a slash. technically you should have to define `matchBase` to only match on the basename

**Comment by jonschlinkert** [comment]
hmmm

**Comment by tunnckoCore** [comment]
> matchBase to only match on the basename

exactly

**Comment by tunnckoCore** [comment]
> can't see how that would be correct.

Im not saying that.

**Comment by es128** [comment]
wait a sec

```
> mm.isMatch('z.js', '**/z*.js')
true
```

looks right to me. The globstar is 0 or more subdirs, and the wildcard adjoined with a (non-separator) char is 0 or more chars.

**Comment by tunnckoCore** [comment]
> should be true.

I dont know why it should be, but this is wrong behavior for me.

**Comment by es128** [comment]
just... intuition?

the globstar part or the zero-width wildcard part - which seems wrong to you?

**Comment by jonschlinkert** [comment]
the thing that makes this seemingly straightforward is that there are use cases where you are both correct. but it's not so "exact". the specification differs based on accompanying patterns.

**Comment by jonschlinkert** [comment]
like this. the following result is correct. I think we would all agree with this, no?

```js
console.log(micromatch.isMatch('z.js', '**/*.js'));
//=> true
```

**Comment by tunnckoCore** [comment]
hm, I dont thinks so. But want to mention that I didn't read the spec. Im not spec specialist.

**Comment by es128** [comment]
Puts [this comment](https://github.com/jonschlinkert/micromatch/pull/16#commitcomment-10459473) in a very different light

**Comment by jonschlinkert** [comment]
I didn't memorize the spec(s) yet, but I did read them. Bash 4.3 and wildmatch (used by git). They follow the same specifications for most cases, but there are holes in both, and differences. 

How about if I come back later with some spec details so that if we continue this discussion we can do so around some hard data?

**Comment by es128** [comment]
http://man7.org/linux/man-pages/man7/glob.7.html is far from comprehensive - but it is very clear about a wildcard `*` character being able to match 0 (empty string) or more characters

**Comment by tunnckoCore** [comment]
its simple.. on bash 4.1
```
GNU bash, version 4.1.2(1)-release (i386-redhat-linux-gnu)
```
i did some tests on the file system

just created following structure
```
a/b.cs
a/k.php
a/z.js
d.js
e.php
z.js
```
and this `ls -al **/*.js` matches only `a/z.js`

**Comment by tunnckoCore** [comment]
so this one
```js
console.log(micromatch.isMatch('z.js', '**/*.js'));
//=> true
```
should be false

**Comment by jonschlinkert** [comment]
> bash 4.1

This follows Bash 4.3.

See: 

- https://github.com/jonschlinkert/micromatch/blob/master/test/bash.js#L20 (this is complete, except for unit tests that had bash variables or patterns that are irrelevant in node. minimatch does not pass all of these, micromatch does)
- https://github.com/jonschlinkert/micromatch/blob/master/test/braces.js#L65 (even though the attribution comment is on line 65, virtually all of those tests are derived from wildmatch)

**Comment by es128** [comment]
add more subdirs: `a/b/c/d/e.js`

does it match?

**Comment by jonschlinkert** [comment]
> should be false

You're making falsey assumptions about the spec.

**Comment by jonschlinkert** [comment]
and don't point out the extglob wildmatch tests lol, that's not even officially supported here yet (nor by  minimatch), but this still passes most of them.

**Comment by es128** [comment]
Here's another reference explaining how globstars are supposed to work, which is consistent with how micromatch currently behaves:

http://www.gnu.org/software/bash/manual/bashref.html#The-Shopt-Builtin-1

**Comment by jonschlinkert** [comment]
that's what I was just reading over, thx.

**Comment by tunnckoCore** [comment]
> does it match?

actually nope, keep matching only `a/z.js`

**Comment by es128** [comment]
eeeexactly

**Comment by jonschlinkert** [comment]
> If the pattern is followed by a ‘/’, only directories and subdirectories match.

This is the part of the spec I was focused on with example above. Minimatch does this, and micromatch does as well. However, like every specification, there are exceptions to this rule. It doesn't apply to every pattern in the specification.

**Comment by jonschlinkert** [comment]
okay, here is micromatch vs minimatch for all of the patterns in the section we've been discussing.

Both libraries yield the same result for all of the following:

```js

console.log(micromatch.isMatch('a/b/c/z.js', '*.js'));
//=> false
console.log(micromatch.isMatch('a/b/z.js', '*.js'));
//=> false
console.log(micromatch.isMatch('a/z.js', '*.js'));
//=> false
console.log(micromatch.isMatch('a/z.js', 'a/b/**/*.js'));
//=> false
console.log(micromatch.isMatch('z.js', 'a/b/**/*.js'));
//=> false

console.log(micromatch.isMatch('a/b-c/d/e/z.js', 'a/b-*/**/z.js'));
//=> true
console.log(micromatch.isMatch('a/b-c/z.js', 'a/b-*/**/z.js'));
//=> true
console.log(micromatch.isMatch('a/b/c/d/e/z.js', 'a/b/**/*.js'));
//=> true
console.log(micromatch.isMatch('a/b/c/d/z.js', 'a/b/**/*.js'));
//=> true
console.log(micromatch.isMatch('a/b/c/z.js', '**/*.js'));
//=> true
console.log(micromatch.isMatch('a/b/c/z.js', 'a/b/**/*.js'));
//=> true
console.log(micromatch.isMatch('a/b/c/z.js', 'a/b/c**/*.js'));
//=> true
console.log(micromatch.isMatch('a/b/c/z.js', 'a/b/c/**/*.js'));
//=> true
console.log(micromatch.isMatch('a/b/z.js', '**/*.js'));
//=> true
console.log(micromatch.isMatch('a/b/z.js', 'a/b/**/*.js'));
//=> true
console.log(micromatch.isMatch('a/z.js', '**/*.js'));
//=> true
console.log(micromatch.isMatch('z.js', '**/*.js'));
//=> true
console.log(micromatch.isMatch('z.js', '**/z*'));
//=> true
console.log(micromatch.isMatch('z.js', '*.js'));
//=> true
```

However, results differ on the following:

```js
// minimatch
console.log(minimatch.makeRe('**/z*.js').test('z.js'));
//=> false
console.log(minimatch('z.js', '**/z*.js'));
//=> true

// micromatch
console.log(micromatch.isMatch('z.js', '**/z*.js'));
//=> false
console.log(micromatch.makeRe('**/z*.js').test('z.js'));
//=> false
```

**Comment by es128** [comment]
I interpret that to mean the difference between `path/to/**` and `path/to/**/`.

I don't see that as at odds with `path/to/**/*.js` matching `path/to/this.js`

**Comment by jonschlinkert** [comment]
> I don't see that as at odds with path/to/**/*.js matching path/to/this.js

no you're right. that would be a match.

**Comment by es128** [comment]
oh interesting, turns out github comments drops a * when there are two in a quote

**Comment by jonschlinkert** [comment]
yeah I just saw that too lol. I had to edit and add backticks

**Comment by es128** [comment]
Why are you getting different results?

```
> mm.isMatch('z.js', '**/z*.js')
true
> mm.makeRe('**/z*.js').test('z.js')
true
```

**Comment by jonschlinkert** [comment]
not with micromatch. minimatch produces a different answer between the two methods

**Comment by es128** [comment]
you show `false` above? just a copypasta mistake maybe?

**Comment by jonschlinkert** [comment]
oh, wait. I think I missed the point. yeah one sec

**Comment by jonschlinkert** [comment]
wanted to double check. yes you're correct. I just didn't update the result in the comments before I pasted. seems important to do lol

**Comment by jonschlinkert** [comment]
ok, corrected

**Comment by jonschlinkert** [comment]
I'm thinking we're in good shape for now. so far, everything seems to be consistent with the spec.

**Comment by es128** [comment]
ok yeah... we have beat this to death

for every example that's been discussed, micromatch's current behavior is **correct**, and the tests are appropriate for keeping it that way

@tunnckoCore I hope satisfactory proof has been provided for you. If not, I'm sorry. But I, for one, am done here.

**Comment by tunnckoCore** [comment]
haha, okey thanks guys. I dont like the results, but okey.

**Comment by es128** [comment]
For reference, if you want a pattern that says one or more subdirs (instead of 0 or more), use `/*/**`

**Comment by tunnckoCore** [comment]
but .. doh. I cant understand why this is true (as shown in examples)
```js
console.log(micromatch.isMatch('z.js', '**/z*.js'));
//=> true
```
and this is false
```js
console.log(micromatch.isMatch('a/z.js', 'a/z*.js'));
//=> false
```

**Comment by es128** [comment]
ah you're right on this one, you've spotted a bug. Second example should be `true`

**Comment by tunnckoCore** [comment]
doh, noooo, opposite :D

**Comment by tunnckoCore** [comment]
first is absolutely wrong for me. and think it, if it have ability to talk it would say "a want dir and something starting with `z`"

**Comment by es128** [comment]
nope, sorry - that's just is not how it's supposed to be. If you want that it would be `*/z*.js`. Or if you want any number (1 or more) of subdirs it's `*/**/z*.js`

**Comment by tunnckoCore** [comment]
> If you want that it would be */z*.js

what?

**Comment by es128** [comment]
> "a want dir and something starting with z"

to express that as a glob: `*/z*`

or if you meant a javascript file `*/z*.js`

one star instead of two. `**` means **zero** or more subdirs. This is very well established at this point.

**Comment by tunnckoCore** [comment]
so one star means **one or more**? lol

**Comment by es128** [comment]
one star means zero or more characters. In the context of being the only thing between path separators, it means exactly one dir.

**Comment by tunnckoCore** [comment]
```js
var micromatch = require('micromatch');

var paths = [
  'd.js',
  'e.php',
  'z.js',
  'a/b.cs',
  'a/k.php',
  'a/z.js',
  'a/b/h.js',
  'a/b/c/z.js'
];

console.log(micromatch.isMatch('z.js', '**/z*.js'));
//=> true
console.log(micromatch.isMatch('a/z.js', 'a/z*.js'));
//=> false

console.log(micromatch(paths, '**/z*.js'));
//=> [ 'z.js', 'a/z.js', 'a/b/c/z.js' ]
console.log(micromatch(paths, '*/z*.js'));
//=> []
console.log(micromatch(paths, '*/*.js'));
//=> [ 'a/z.js' ]
console.log(micromatch(paths, '**/*.js'));
//=> [ 'd.js', 'z.js', 'a/z.js', 'a/b/h.js', 'a/b/c/z.js' ]
console.log(micromatch(paths, '*z*.js'));
//=> [ 'z.js' ]
console.log(micromatch(paths, '**z*.js'));
//=> [ 'z.js', 'a/z.js', 'a/b/c/z.js' ]

```

**Comment by es128** [comment]
You've identified one bug and represented it twice in these examples:

```js
console.log(micromatch.isMatch('a/z.js', 'a/z*.js'));
//=> should be true
console.log(micromatch(paths, '*/z*.js'));
//=> should be [ 'a/z.js' ]
```

And then potentially one more with that last example, although it's a more academic case that wouldn't be found among anyone's legitimate use cases.

**Comment by tunnckoCore** [comment]
and multimatch

```js
// multimatch

console.log(multimatch(paths, '**/z*.js'));
//=> [ 'z.js', 'a/z.js', 'a/b/c/z.js' ]
console.log(multimatch(paths, '*/z*.js'));
//=> [ 'a/z.js' ]
console.log(multimatch(paths, '*/*.js'));
//=> [ 'a/z.js' ]
console.log(multimatch(paths, '**/*.js'));
//=> [ 'd.js', 'z.js', 'a/z.js', 'a/b/h.js', 'a/b/c/z.js' ]
console.log(multimatch(paths, '*z*.js'));
//=> [ 'z.js' ]
console.log(multimatch(paths, '**z*.js'));
//=> [ 'z.js' ]
```

**Comment by jonschlinkert** [comment]
@tunnckoCore can I just ask why you're doing this? you said you don't use this, but you're trying your best to find bugs - which IMO is fine b/c it helps us, but I don't get the impression you're pointing out flaws to try to be helpful here.

**Comment by tunnckoCore** [comment]
b/c I will use it, but it looks wrong to me.

nevermind

**Comment by es128** [comment]
Yeah we're just going to have to move on. 

@tunnckoCore you've made your point that you disagree with how globstar is intended to work as agreed upon in every spec and implementation we can find, but that's how it is (and it isn't an arbitrary decision by @jonschlinkert nor I that you can talk us out of). I'd suggest you either adjust your understanding or just refrain from using globstar functionality in your glob patterns.

Your (constructive) feedback continues to be welcome (at least as far as I'm concerned), and thank you for helping to uncover two new bugs.
