### ISSUE TITLE
Double-asterisk without path separator (globstar confusion)

### ISSUE THREAD

**Issue by es128** [jonschlinkert/micromatch#20]
Reposting from #15 

```js
console.log(micromatch(paths, '**z*.js'));
//=> [ 'z.js', 'a/z.js', 'a/b/c/z.js' ]

//multimatch
console.log(multimatch(paths, '**z*.js'));
//=> [ 'z.js' ]
```

**Comment by tunnckoCore** [comment]
it's interesting what should be.

**Comment by jonschlinkert** [comment]
@es128 I've been fighting off a cold. just got back on a bit ago, trying to catch up with what's happening. I'll take a look at this in micromatch.

**Comment by es128** [comment]
Alright, don't worry about it. There is no SLA. Hope you're feeling better.

**Comment by jonschlinkert** [comment]
lol true. and thank you.
