### ISSUE TITLE
dot not properly escaped in expandFilename

### ISSUE THREAD

**Issue by es128** [jonschlinkert/micromatch#23]
These should return `false`

```js
> mm.isMatch('zzjs', 'z*.js')
true
> mm.isMatch('zzjs', '*z.js')
true
```

With a directory in the pattern, it behaves correctly because the dot gets escaped
```js
> mm.isMatch('a/zzjs', 'a/*z.js')
false
> mm.isMatch('a/zzjs', 'a/z*.js')
false
```

**Comment by jonschlinkert** [comment]
I'm working on these patterns today. thanks for the detail, that helps
