### ISSUE TITLE
Release 2.2.0

### ISSUE THREAD

**Issue by es128** [jonschlinkert/micromatch#27]
Just trying to gather all the outstanding points discussed recently to be resolved prior to release. Anything is still open to discussion if there remains any disagreement about any of these points.

@jonschlinkert In the future if you want to do your changes in branches/PRs I'd be happy to review and I think it would make it easier to keep all feedback and resolution organized.

- [x] Ensure `extglob`, `braces`, and `brackets` parsing are enabled by default
- [x] Drop the options as above in favor of the `no*` alternatives
- [x] Support `nobrace` option as alias for `nobraces` for minimatch parity
- [x] Tests to ensure both `nobrace` and `nobraces` remain supported at least until a major version bump
- [x] Ensure readme documentation accurately reflects all of the above
- [x] Fix readme anchor links
- [x] Update benchmarks & browser build

**Comment by jonschlinkert** [comment]
> In the future if you want to do your changes in branches/PRs I'd be happy to review and I think it would make it easier to keep all feedback and resolution organized.

sounds good to me, I really like the format you follow.

**Comment by jonschlinkert** [comment]
also I have several fixes I'll be pushing up in a bit. the docs are getting a bit long, I might generate a basic gh-pages site at some point.

**Comment by jonschlinkert** [comment]
@es128 what's the best way to get in touch outside of github? my email is on my profile if you want you to shoot me an email.

**Comment by es128** [comment]
@jonschlinkert sent

**Comment by jonschlinkert** [comment]
replied! thanks

**Comment by tunnckoCore** [comment]
> Ensure extglob, braces, and brackets parsing are enabled by default

erm, enabled? hm, when i read the whole readme i noticed that they are "undefined by default".

**Comment by es128** [comment]
>  Ensure readme documentation accurately reflects all of the above

**Comment by jonschlinkert** [comment]
@es128 sorry this is taking so long. I have a few fixes to push up to a brach that might get us 90% of the way there.

also, @doowb and I [created this](https://github.com/jonschlinkert/snapdragon) as an attempt at making this easier to maintain, but I don't know how the speed is comparatively yet. if you feel like playing around with it, feedback would be great!

**Comment by tunnckoCore** [comment]
@jonschlinkert WOW! examples looks awesome! benchmarks need.

**Comment by jonschlinkert** [comment]
thanks! it's a pretty fun project. @doowb and I have been wanting to create a project like that for a while. @doowb wrote some code for the parser stuff and had some awesome ideas for how parsers could be used by other parsers. we finally decided to just get it implemented.

is there a use case for having sourcemaps with glob patterns? lol:

```js
{ code: 'foo\\/(a|b|c)\\/bar\\/\\{xyz\\}\\/baz.js',
  map:
   { version: 3,
     sources: [ 'string' ],
     names: [],
     mappings: 'AAAA,GAAG,EAAC,CAAC,KAAK,CAAN,OAAO,EAAC,GAAG,EAAC,EAAE,GAAG,EAAC,EAAC,GAAG' } }
``

**Comment by jonschlinkert** [comment]
and fwiw, that's just one use case. I'd like to use snapdragon to refactor the parsers for braces, expand-brackets, extglob, parse-comments, etc.

**Comment by tunnckoCore** [comment]
> thanks! it's a pretty fun project.

Yea, I also had some idea like that, but on per single character basis with some thin api on top like in snapdragon are `this.match()` and `this.position()` methods exposed. But it is more for css parsing.

But yea, looks pretty good and composable. Their codebase will look better definitely.

okey, that's offtopic, lol. gj

**Comment by es128** [comment]
@jonschlinkert no worries about the delay, I'm similarly tied up. I had just as much aspiration to tackle this checklist, didn't mean to just put it all on you.

Snapdragon looks like an awesome concept. Looking forward to seeing what can come of it.

**Comment by jonschlinkert** [comment]
@es128 I believe all of the above are checked off. please see: https://github.com/jonschlinkert/micromatch/tree/2.2.0 and publish when you're good with everything. 

Regarding the `no*` options, I think it makes more sense to keep the `no*` options and drop the others, since there are a lot of options prefixed with `no*` in both bash and minimatch. 

also I'm good with doing a 3.0 if you want. I'm still planning on pushing up a complete refactor asap, but I don't want to hold up the fixes that have been waiting here for a while any longer than necessary.

**Comment by es128** [comment]
Awesome. Will try to take some time to review later today.

**Comment by jonschlinkert** [comment]
thanks!

**Comment by jonschlinkert** [comment]
and no rush...

**Comment by es128** [comment]
> Regarding the no* options, I think it makes more sense to keep the no* options and drop the others, since there are a lot of options prefixed with no* in both bash and minimatch.

yes, cool. that appears to be the same thing I suggested in my checklist. good thing I left that there because my memory on all this has gotten very fuzzy

taking a look now

**Comment by es128** [comment]
What's the deal with the skipped test?

These are the assertions that fail

```js
mm.match(['foo'], '!(foo)*').should.eql(['foo']);
mm.match(['foobar'], '!(foo)*').should.eql(['foobar']);
mm.match(['moo.cow'], '!(*.*).!(*.*)').should.eql(['moo.cow']);
mm.match(['fff'], '*(!(f))').should.eql(['fff']);
mm.match(['fff'], '+(!(f))').should.eql(['fff']);
mm.match(['foo'], '*(!(f))').should.eql(['foo']);
mm.match(['foo'], '+(!(f))').should.eql(['foo']);
mm.match(['foo'], '*(!(foo))').should.eql(['foo']);
mm.match(['foobb'], '!(foo)b*').should.eql(['foobb']);
```

**Comment by es128** [comment]
It would appear in each case that the negation operator is applying to more than just the parens-separated section it was intended to apply to

**Comment by jonschlinkert** [comment]
those tests are from the `extglob` spec. IMHO those shouldn't be expected to pass for this release to be published. micromatch already has better extglob support than minimatch, in the refactor I'm working on those cases are much easier to solve

**Comment by jonschlinkert** [comment]
doh, and yeah you did say that about the `no*` options... for some reason I got it in my mind that you were saying the other way around

**Comment by es128** [comment]
Ok, so that just leaves the question of whether 2.2.0 or 3.0.0.

Based on a perusal of https://github.com/jonschlinkert/micromatch/compare/2.1.6...2.2.0 I don't see any previously published options being removed (they were added and removed without ever being published afaict). Taken with the passing unit tests (no significant tests removed or stopped working compared with before) - seems like 2.2.0 would be right. Right?

You have my sign off. Not sure how you'd handle the merge conflicts with master (has to do with the verb docs, and I don't quite know your workflow there), so will leave it to you.

**Comment by jonschlinkert** [comment]
:+1: sounds good. 2.2.0 is fine with me. I'll get it published

**Comment by es128** [comment]
ping

If you want me to go ahead and figure this out I could probably spare some time for it

**Comment by jonschlinkert** [comment]
that would be awesome! thanks. I'm not 100% sure but I think all that needs to be handled is the merge conflicts with the readme. I'd be happy to generate the docs with verb and updated it once that's done.

**Comment by es128** [comment]
Yup that was it. I went ahead and cleared the conflict in the 2.2.0 branch, preserving the version of the readme that was already there. Took a quick look at the verb docs, but it wasn't immediately apparent how to regenerate the docs again to ensure they're up to date.

**Comment by jonschlinkert** [comment]
great! no prob I can do the verb docs. I'll take a look in a bit

**Comment by tunnckoCore** [comment]
when to expect refactored micromatch? im excited how it looks with snapdragon.

**Comment by jonschlinkert** [comment]
ha, me too.. that pattern is so much cleaner and (so far) faster. fun too. I'm making progress... :)

**Comment by jonschlinkert** [comment]
going to have to merge tomorrow. I'll do this first thing.

**Comment by chimurai** [comment]
@jonschlinkert is v2.2.0 supposed to be backwards-compatible with v2.1.6?

I'm getting different behavior with default options:

v2.1.6
micromatch(['/api/foo/bar.html'], '**.*')
//=> ['/api/foo/bar.html']

v2.2.0
micromatch(['/api/foo/bar.html'], '**.*')
//=> []

Looking forward to future releases. Keep up the good work! :)

**Comment by es128** [comment]
@chimurai the semver minor bump indicates API backward compatibility, not necessarily matching behavior. 

If you believe you've identified a bug or regression please open a separate issue about it.

**Comment by es128** [comment]
Closing since 2.2.0 has been published.

**Comment by jonschlinkert** [comment]
> I'm getting different behavior with default options:

I think micromatch should handle that example properly in 2.2.0. Paths that begin with `/` are absolute paths and should only be matched by globs that start with `/`... yeah definitely let us know if you find a bug with this release

**Comment by jonschlinkert** [comment]
and thanks @es128!
