### ISSUE TITLE
false on regex group matching

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/micromatch#31]
with `is-match`

```js
var matcher = require('is-match')
var isMatch = matcher(['123.[71-79].34.*'])

console.log(isMatch('123.77.34.89'))
//=> false
```

**Comment by es128** [comment]
Why'd you open the issue here instead of at is-match?

**Comment by tunnckoCore** [comment]
cuz it is based on micromatch in that case. ^^

**Comment by tunnckoCore** [comment]
https://github.com/jonschlinkert/is-match/blob/master/index.js#L29-L33

**Comment by es128** [comment]
Ok. But so, shouldn't your regex be an actual regex instead of a string?

**Comment by tunnckoCore** [comment]
erm? with title i mean `regex matching group` functionality of micromatch.

https://github.com/jonschlinkert/micromatch#regex-character-classes
https://github.com/jonschlinkert/micromatch#regex-groups

**Comment by es128** [comment]
Ok yeah I get it now. Sorry for the noise

**Comment by tunnckoCore** [comment]
@es128 no problem :)

**Comment by jonschlinkert** [comment]
@tunnckoCore thanks will look into it. Can you tell me if it works if the numbers are letters? it might be a simple fix

**Comment by tunnckoCore** [comment]
@jonschlinkert mm yea, this works

```js
var matcher = require('is-match')
var isMatch = matcher(['123.[a-z].34.*'])

console.log(isMatch('123.g.34.89'))
//=> true
```

**Comment by jonschlinkert** [comment]
so it does work with alpha but not numeric... Okay, that's probably a pretty simple fix.

**Comment by jonschlinkert** [comment]
oh, wait I just realized something. you're technically using an invalid regex range in the character class (`[71-77]`).

this is still a bug, but it might be a different bug than I thought... in the meantime, here is what I suspect is happening. since you used `[a-z]` in the alpha example, and that happened to be a valid range, it worked. It might have been because it was alpha, but it might not. 

So, if you use an invalid **alpha** range, that should **not** match any thing, because there is no logic that can make an invalid alpha-range in a glob pattern to be correct in a regex. However, if the range is numeric, and it's "logically" valid in glob patterns but invalid in a regex character class, we can expand it to look like `(?:71|72|73|74|75|76|77)`. I suspect this is not happening right now, but it should be. If it's not, the problem is probably in fill-range.

**Comment by jonschlinkert** [comment]
or... we just stay strict and make you use braces instead. try doing this:

```js
var isMatch = matcher(['123.{71..79}.34.*'])
```

**Comment by jonschlinkert** [comment]
one more point of clarification, I don't mean that it's invalid regex, just that it's an invalid range. e.g. `[71-79]` will match, `7`, `1`, `-`, or `9`.

**Comment by jonschlinkert** [comment]
var repeat = require('repeat-string');

function fill(val, num) {
  var str = String(val);
  var neg = str.charAt(0) === '-';
  var len = num - str.length;
  if (neg) {
    val = str.slice(1);
  }
  var res = repeat('0', len || 0) + val;
  return neg ? '-' + res : res;
}

function pad(a, b, len, step) {
  step = step || 1;
  var res = [];

  a = +a;
  b = +b;
  var des = a > b;
  var n = a;

  while (des ? (n >= b) : (n <= b)) {
    n = (des ? n-- : n++);
    res.push(fill(n, len));
    n = des ? (n - step) : (n + step);
  }
  return res;
}
// console.log(pad(2, 10, 3));
// console.log(pad(10, 2, 3));
// console.log(pad(5, -5, 10));
// console.log(pad(-5, 5, 4));

function len(a, b) {
  if (!isPadded(a) && !isPadded(b)) {
    return 0;
  }
  var alen = a.length, blen = b.length;
  var max = alen >= blen ? alen : blen;
  return Math.abs(max);
}

function padStr(a, b, step) {
  return pad(a, b, len(a, b), step);
}

function isPadded(val) {
  return /^-*0+[0-9]/.test(val);
}

function toRegexp(str) {
  var orig = str;
  str = str.slice(1, str.length - 1);
  var arr = str.split('-');
  var a = arr[0];
  var b = arr[1];

  if (a === b) {
    res = '[' + a + ']';
  }
  if (a < b && (a < 0 || b > 9) || a > b) {
    var arr = padStr.apply(padStr, str.split('-'));
    if (arr.length) {
      res = '^(' + arr.join('|') + ')$';
    } else {
      res = orig;
    }
  }

  try {
    return new RegExp(res);
  } catch(err) {
    return new RegExp(str.split('').join('\\'));
  }
}

console.log(toRegexp('[71-77]'))
console.log(toRegexp('[77-71]'))
console.log(toRegexp('[61-70]'))
console.log(toRegexp('[a-70]'))

**Comment by tunnckoCore** [comment]
> try doing this:

yea, I thought that will help, but what to ping you about that case ("bug"/wrong expectation), cuz it was strange to me. But when I think.. have logic, yea.

> you're technically using an invalid regex range in the character class

invalid? why? it's not invalid. but it's wrong to expect what I expected, lol.

```js
console.log(/.*([44-78]+).*/g.test('abc 123% foo bar'))
//=> false

console.log(/.*([44-78]+).*/g.test('abc 11% foo bar'))
//=> false

console.log(/.*([44-78]+).*/g.test('abc 153% foo bar'))
//=> true

console.log(/.*([44-78]+).*/g.test('abc 65% foo bar'))
//=> true
```

**Comment by tunnckoCore** [comment]
@jonschlinkert feel free to close ;]

**Comment by jonschlinkert** [comment]
> invalid? why? it's not invalid.

it is an invalid **regex range**, it's not "invalid" in an absolute sense: http://www.regular-expressions.info/numericranges.html. It just won't match what you're expecting as a range. 

Example

```js
console.log(/.*([44-78]+).*/g.test('abc 65% foo bar'))
//=> matches 4, 4-7, and 8. 
```
Try

```js
console.log(/.*([44-78]+).*/g.test('abc 55% foo bar'))
```

**Comment by jonschlinkert** [comment]
k, I will go ahead and close because I think it makes more sense to just stick with regex rules.

**Comment by tunnckoCore** [comment]
> I think it makes more sense to just stick with regex rules.

yea, yea, you're right. as i said my fault

**Comment by jonschlinkert** [comment]
no prob!
