### ISSUE TITLE
problem (not so) matching urls

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/micromatch#34]
I realize that it is because of `filepaths globbing` idea, but it's uncomfortable when trying to match urls.

```js
var matcher = require('is-match')

matcher('https://github.com/*')('https://github.com/tunnckoCore')
//=> false

matcher('https://github.com**/**')('https://github.com/tunnckoCore')
//=> false

matcher('https://github.co**/**')('https://github.com/tunnckoCore')
//=> false

matcher('https://github.com/**/**')('https://github.com/tunnckoCore')
//=> false

matcher('https://github.com/**/*')('https://github.com/tunnckoCore')
//=> false

matcher('http*')('https://foo.com')
//=> false

matcher('http**/*')('https://foo.com')
//=> false

matcher('http*/**')('https://foo.com')
//=> true

matcher('http**/**')('https://foo.com')
//=> true
```

using `chorks/is-match#master` (waiting merge PR) which uses micromatch `v2.1.6`

Maybe Im missing some option? Or we should add some option? :D

**Comment by jonschlinkert** [comment]
Do all of these work with minimatch? I'm thinking this is a great example of what I'd like to use middleware for in the refactor.

**Comment by tunnckoCore** [comment]
Hm, i will try.

**Comment by tunnckoCore** [comment]
@jonschlinkert yea, returns `true` for all except that (fourth from bottom to top)

```
console.log(minimatch('https://foo.com', 'http*'))
//=> false
```

**Comment by jonschlinkert** [comment]
all we need to do is strip `https://` or whatever protocol it is from the path before testing it. really though I'm not sure it's something that minimatch or micromatch should do

**Comment by tunnckoCore** [comment]
> I'm not sure it's something that minimatch or micromatch should do

agreed, but it should be possible to compare things like that

**Comment by es128** [comment]
I don't think micromatch should start making special accomodations for this, but @tunnckoCore you could just use [`url.parse().pathname`](https://nodejs.org/api/url.html) to do glob-style matching against the url paths (and just compare hostnames directly if you need that too). 

Although maybe what you really want is something more along the lines of a [client-side router](https://github.com/ampersandjs/ampersand-router)?

**Comment by jonschlinkert** [comment]
> Although maybe what you really want is something more along the lines of a client-side router?

that's exactly what @doowb and I were thinking. I asked @doowb his opinion too, I wasn't sure - it seems like a nice to have

**Comment by es128** [comment]
> seems like a nice to have

I'd say if there is a need for such a thing (glob-style matching on urls) it should be done in a separate module. micromatch should not start down this road. 

Then, if something like is-match wanted to support both simultaneously by using the two dependencies, it could.

**Comment by tunnckoCore** [comment]
I dont know. Actually i won't use it for that and know that there is some ways to do it. But it appears from one usage example for `object.validate` that i'll push up in a bit and i was lil bit surprised, but then realized why is happening.

**Comment by jonschlinkert** [comment]
k we can keep this in mind for a non-built-in middleware for the next version. closing since we all would probably rather see the next version than to add features now anyway
