### ISSUE TITLE
regression v2.2.0

### ISSUE THREAD

**Issue by chimurai** [jonschlinkert/micromatch#36]
Possible regression with default micromatch options. https://github.com/jonschlinkert/micromatch/issues/27#issuecomment-124574227

The first two examples don't match anymore after upgrading to v2.2.0.
Looks like it doesn't match when pattern starts with globstar (`**`) and no slashes (`/`) are present in the pattern.

*v2.2.0*
```
micromatch(['/api/foo/bar.html'], '**.*')          //  regression?
//=> []

micromatch(['/api/foo/bar.html'], '**.html')       //  regression?
//=> []

micromatch(['/api/foo/bar.html'], '/**.*')
//=> ['/api/foo/bar.html']

micromatch(['/api/foo/bar.html'], '/**.html')
//=> ['/api/foo/bar.html']

micromatch(['/api/foo/bar.html'], '/**/*.*')
//=> ['/api/foo/bar.html']
```

*v2.1.6*
```
micromatch(['/api/foo/bar.html'], '**.*')
//=> ['/api/foo/bar.html']

micromatch(['/api/foo/bar.html'], '**.html')
//=> ['/api/foo/bar.html']

micromatch(['/api/foo/bar.html'], '/**.*')
//=> ['/api/foo/bar.html']

micromatch(['/api/foo/bar.html'], '/**.html')
//=> ['/api/foo/bar.html']

micromatch(['/api/foo/bar.html'], '/**/*.*')
//=> ['/api/foo/bar.html']
```

**Comment by jonschlinkert** [comment]
see https://github.com/jonschlinkert/micromatch/issues/27#issuecomment-124578854. all of those results look correct to me

**Comment by chimurai** [comment]
Ah... so I've been using the pattern incorrectly.
Thanks for the clarification!

Closing the issue.

**Comment by jonschlinkert** [comment]
no prob, thank you for creating the issue. there are probably others wondering as well!
