### ISSUE TITLE
Dot directory and {* /} combination is not working

### ISSUE THREAD

**Issue by masakura** [jonschlinkert/micromatch#38]
Dot directory and {* /} combination is not working

Start dot directory, failed.

```
> mm.isMatch('.a/xyz.md', '.a/{,*/}xyz.md')
false
> mm.isMatch('.a/xyz.md', '.a/**/xyz.md')
false
```

Start not dot directory, success.

```
> mm.isMatch('a/xyz.md', 'a/{,*/}xyz.md')
true
> mm.isMatch('a/xyz.md', 'a/**/xyz.md')
true
```

**Comment by jonschlinkert** [comment]
thanks for reporting, marking as a bug

**Comment by tconroy** [comment]
Status on this issue?

**Comment by jonschlinkert** [comment]
I'm working on the next version of this and got sidetracked and forgot to come back to this. sorry I'll try to take a look today.

**Comment by tconroy** [comment]
No worries, thank you for your hard work :)

**Comment by callumlocke** [comment]
I see a bunch of commits... Can this be closed now?

**Comment by jonschlinkert** [comment]
I think I just need to publish 0.2.3. sorry for the delay, it's on my priority list for today
