### ISSUE TITLE
Double globstar does not play well with backslashes

### ISSUE THREAD

**Issue by aleclarson** [jonschlinkert/micromatch#39]
This seems to be a bug.

```js
mm('/user.js', '**.js')
// expected => true
// got      => false
```

&nbsp;

Everything works great if a `/` is nowhere in the string; as seen below.

```js
mm('user.js', '**.js')
// expected => true
// got      => true
```

&nbsp;

Using `**/*.js` instead is a workaround.

```js
mm('/user.js', '**/*.js')
// expected => true
// got      => true

mm('user.js', '**/*.js')
// expected => true
// got      => true
```

&nbsp;

NodeJS v0.12.4
micromatch v2.2.0

**Comment by es128** [comment]
You're showing slashes, not backslashes, throughout your example, but perhaps it doesn't make a difference.

`**.js` isn't really the way globstar is intended to to be used, and I think double-asterisk gets collapsed to single when it isn't alone as a path part (meaning it should be expanded to n-depth subdirectories). 

So given that, this does not look like a bug. In each case of what you're describing as unexpected results, you're comparing paths/globs at different path depths. A leading slash indicates a root path, whereas the lack of one in the glob pattern means you start at `cwd`.

Closing based on my interpretation, but maybe @jonschlinkert will still want to chime in.
