### ISSUE TITLE
What is the difference between matcher and filter?

### ISSUE THREAD

**Issue by callumlocke** [jonschlinkert/micromatch#40]
This might be a documentation issue, or maybe I'm being stupid.

The readme says that [.matcher(pattern)](https://github.com/jonschlinkert/micromatch#matcher) gets you a function that you can use to match paths. I'm assuming this means it returns true/false, in which case it sounds like it could be used as an array filter function.

But then there seems to be another method for this exact purpose, [.filter()](https://github.com/jonschlinkert/micromatch#filter): "Returns a function that can be passed to `Array#filter()`." I don't get it. Can't the returned function from .matcher be used in this way?

What's the difference?

**Comment by es128** [comment]
I can't speak to why both needed to be provided in the API, but here's the difference as far as I can tell:

`filter` works with one or more glob patterns. 

`matcher` works with one criterion (not an array) and allows regexes and functions as well as glob patterns as the input.

**Comment by jonschlinkert** [comment]
Yeah, the differences that @es128 pointed out are correct, but I've thought about removing filter. Maybe we can allow `matcher` to handle multiple patterns, and get rid of filter next time we make major changes

**Comment by callumlocke** [comment]
> Maybe we can allow matcher to handle multiple patterns, and get rid of filter next time we make major changes

That sounds good, less confusing.

In the mean time, do I understand correctly that `mm.filter(x)(filename)` should always work identically to `mm(x, filename)`, no matter what `x` is?

**Comment by jonschlinkert** [comment]
What's the use case? might be easier to give good feedback based on what you're trying to accomplish.

**Comment by callumlocke** [comment]
The `mm()` function works like this:

> **Negation patterns:**
> Behavior;
> - when the pattern is a string, minimatch behavior is used, so patterns are **inclusive by default**.
> - when an array of patterns is passed, multimatch behavior is used, so patterns are **exclusive by default**

Does the function I get back from `mm.filter(x)` have that same behaviour (i.e. it can either be inclusive or exclusive, depending on whether `x` is an array or a string)?

**Comment by jonschlinkert** [comment]
> can [filter] either be inclusive or exclusive, depending on whether x is an array or a string)?

it should, yes. see [these unit tests](https://github.com/jonschlinkert/micromatch/blob/master/test/filter.js#L43-L58) for examples

**Comment by jonschlinkert** [comment]
closing since it's not technically an issue. feel free to continue the conversation or open a new issue if a new topic pops up
