### ISSUE TITLE
Issue when using negations against /'s

### ISSUE THREAD

**Issue by zackehh** [jonschlinkert/micromatch#42]
This might just be me being stupid, but I want to check :)

Can someone please clarify the state of these two globs? Afaik they should both match?

```
# matches
mm.any('/target/build', ['/target/!(dist)'])

# doesn't match
mm.any('/target/build/classes', ['/target/!(dist)'])
```

I'm not too familiar with globs so maybe I'm missing something. I guess the potential to have a `/...` after is throwing it off?

`mm.any('/target/build/classes', ['!/target/dist'])` matches too, but in my use case the `/target/` prefix might be changing, so I can't just hardcode that section of the pattern.

Thanks in advance! Great library, very nice to use.

**Comment by jonschlinkert** [comment]
looks like `mm.any('/target/build', ['/target/!(dist)'])` should match, but I think `mm.any('/target/build/classes', ['/target/!(dist)'])` should not.  I'm pretty sure the latter should work if you do:

```js
mm.any('/target/build/classes', ['/target/!(dist)/*'])
```

So I think that's right. Let me know if that works

**Comment by zackehh** [comment]
@jonschlinkert perfect, the tip on the `**` is exactly what I needed. It works perfectly, thanks for your help!

**Comment by jonschlinkert** [comment]
glad it worked! happy to help
