### ISSUE TITLE
Does not handle `+` properly

### ISSUE THREAD

**Issue by UltCombo** [jonschlinkert/micromatch#45]
Test case:

```js
micromatch.isMatch('coffee+/src/glimini.js', 'coffee+/src/**');
```

Actual: `false`
Expected: `true`

Tested with micromatch@2.2.0.

**Comment by jonschlinkert** [comment]
thanks for reporting. I'll look into it asap

**Comment by jonschlinkert** [comment]
this should be a pretty simple fix. basically `+` is recognized as a regex character, so it's trying to match _one or more `e` characters_, but we need it to match a literal `+` instead. I'll get a patch pushed up.

**Comment by UltCombo** [comment]
That makes sense. Though, as far as I can see, the `+` character is properly listed in the [`chars.escapeRegex`](https://github.com/jonschlinkert/micromatch/blob/5017fd78202e04c684cc31d3c2fb1f469ea222ff/lib/chars.js#L17). I'm not familiar enough with this code base to know what is going wrong.

**Comment by jonschlinkert** [comment]
no worries, I'll track it down. I'm pretty sure I know where it is. that character is used in both extglobs and brace expansion - but, neither would be causing this issue since they match fairly specific patterns.

if you have any more ideas for test cases I can add to the unit tests, that would be great.

**Comment by jonschlinkert** [comment]
@UltCombo could you try your test case against [this patch](https://github.com/jonschlinkert/micromatch/tree/issue-45-plus-literal) and see if that works for you?

**Comment by UltCombo** [comment]
Oh nice, I'll try it tonight. :smile:

**Comment by UltCombo** [comment]
Works great, thanks for the quick fix! :smile_cat:

**Comment by jonschlinkert** [comment]
great! no problem of course, I appreciate you creating an issue. I'll get a patch pushed up shortly
