### ISSUE TITLE
Travis Error: Failed resolving git HEAD (https://github.com/jonschlinkert/micromatch

### ISSUE THREAD

**Issue by phun-ky** [jonschlinkert/micromatch#46]
Just got this error in our Travis build, it's a subdependency (karma - anymatch - micromatch )

    npm ERR! Failed resolving git HEAD (https://github.com/jonschlinkert/micromatch) fatal: ambiguous argument '2.3.0': unknown revision or path not in the working tree.

    npm ERR! Failed resolving git HEAD (https://github.com/jonschlinkert/micromatch) Use '--' to separate paths from revisions, like this:

    npm ERR! Failed resolving git HEAD (https://github.com/jonschlinkert/micromatch) 'git <command> [<revision>...] -- [<file>...]'

    npm ERR! Failed resolving git HEAD (https://github.com/jonschlinkert/micromatch) 

_This issue probably do not belong here, but I put it here for others to be aware of the issue_

Could this be a version mismatch at your end, or is this a result of bad dep version range in a dependency?

**Comment by es128** [comment]
Is the issue resolved now, or can you still reproduce it with a new build?

**Comment by phun-ky** [comment]
I've still got the issue reproduced on Travis 24 minutes ago

**Comment by es128** [comment]
Is it a public project you can link to?

**Comment by jonschlinkert** [comment]
yeah any additional info would be great. I'm not sure how to reproduce

**Comment by jonschlinkert** [comment]
I know what's causing it. something is hard-wired to use a git branch that I removed when I merged - it's now restored. seems like a good argument for not deleting git branches for versions. 

did this resolve the issue for you?

**Comment by es128** [comment]
@phun-ky to be clear, if this is the case, you really should replace the direct git reference with a regular npm registry install at this point. If you're going to override npm and install directly from git you have to take responsibility for maintaining that within your project.

**Comment by phun-ky** [comment]
It's probably the case, but not from my side, I don't use direct git reference to micromatch in my project. It's not a public one, so I can't give more information. I believe it comes from karma -> anymatch (anymatch depends on micromatch).

Will keep you up to date

**Comment by es128** [comment]
anymatch is mine - it does not use a git reference

**Comment by phun-ky** [comment]
hm, will try to force a npm clean cache

**Comment by phun-ky** [comment]
It's fixed now, `npm cache clean` did the trick!

**Comment by es128** [comment]
Good to hear. Thanks for letting us know.

**Comment by jonschlinkert** [comment]
great! glad it's resolved
