### ISSUE TITLE
2.3.6 housekeeping

### ISSUE THREAD

**Issue by jonschlinkert** [jonschlinkert/micromatch#47]
for starters...

- replace gulp-jshint with gulp-eslint
- lint (I expect this to result in a bunch of small changes since we'll be using a much more stringent linting config)

I'm planning on doing this in the next patch. anything to add @es128?

**Comment by es128** [comment]
* review minimatch options object, ensure as much parity as possible

(I'm not aware of any gaps, but related to the glob-stream PR it could probably use a once-over to be safe)

**Comment by jonschlinkert** [comment]
good idea

**Comment by jonschlinkert** [comment]
and thanks for that doing that pr, regardless of whether they decide on merging I appreciate it!

**Comment by jonschlinkert** [comment]
@es128 I just pushed up 2.3.6. It's just a patch - the vast majority of changes are whitespace or similar things from switching to eslint. fortunately that only needs to be done once.

also included in the patch:

- bumps lazy-cache to 1.0. There were no API changes in lazy-cache, we just bumped to per https://github.com/jonschlinkert/micromatch/issues/52
- documentation updates

Once you review, assuming you have no objections, let me know and I'll publish (or you can if you want).

Thanks!

**Comment by jonschlinkert** [comment]
@es128 I'm like to go ahead and merge this unless you have any last minute objects

**Comment by es128** [comment]
It was already merged last week I thought

**Comment by jonschlinkert** [comment]
I meant publish, sorry for confusion. I think it's still at 2.3.5, I have a Board meeting but will be able to look in about an hour or so.

**Comment by es128** [comment]
No objections. Go ahead and publish at will.

**Comment by jonschlinkert** [comment]
done
