### ISSUE TITLE
Doesn't work in webpack

### ISSUE THREAD

**Issue by fazo96** [jonschlinkert/micromatch#55]
Webpack can't build this because it has requires that can't be resolved statically (without executing the code)

The problem is of course in https://github.com/jonschlinkert/micromatch/blob/master/lib/utils.js

This makes micromatch not a drop in replacement in environments where webpack is used.

I know this sounds like a harsh critique, but just wanted to let you know about the issue :+1:

**Comment by jonschlinkert** [comment]
We've already created an issue on webpack and have discussed this at length elsewhere. I don't expect a solution there anytime soon given that there are 490 other issues.

> This makes micromatch not a drop in replacement in environments where webpack is used.

Webpack requires custom plugins and loaders to work in many scenarios, this is no different. 

I think @doowb was working on a webpack loader that might help with this, we can link it here if/when that's published.

**Comment by jonschlinkert** [comment]
I've unlazied micromatch, so this should be fixed. 

although I still think this is a bug or limitation in webpack, it's just impossible to keep up with the number of webpack users who wouldn't have any way of knowing that.

**Comment by eephillip** [comment]
Looks like this makes a come back in versions matching `^3.0.0`

```
WARNING in ../~/base/utils.js
3:34-41 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ../~/define-property/~/is-descriptor/utils.js
7:34-41 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ../~/is-descriptor/utils.js
7:34-41 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ../~/use/utils.js
3:34-41 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

ERROR in ../~/snapdragon/lib/source-maps.js
Module not found: Error: Can't resolve 'fs' in '/Users/app/node_modules/snapdragon/lib'
 @ ../~/snapdragon/lib/source-maps.js 3:9-22
 @ ../~/snapdragon/lib/compiler.js
 @ ../~/snapdragon/index.js
 @ ../~/micromatch/lib/utils.js
 @ ../~/micromatch/index.js
 @ ./js/app.js

**Comment by doowb** [comment]
Use [unlazy-loader](https://github.com/doowb/unlazy-loader)
