### ISSUE TITLE
comparison to minimatch

### ISSUE THREAD

**Issue by jonschlinkert** [jonschlinkert/micromatch#6]
Since minimatch is so heavily used, a comparison between micromatch and minimatch might help devs see where this lib is superior. 

For starters: here is the difference between the matching regex generated by micromatch and minimatch:  https://gist.github.com/jonschlinkert/ef4ee3bab2d78b50b323

**Comment by es128** [comment]
I'd particularly like a comparison of API differences - i.e. can micromatch be used as a drop-in replacement for minimatch?

**Comment by jonschlinkert** [comment]
@es128 you got, I'll work something up.

**Comment by jonschlinkert** [comment]
Here is a start: https://gist.github.com/jonschlinkert/96212e11d128fc659d12. fwiw I tend to be wordy when I start something, then try to reduce it down as I get it filled in. It's not finished but at least you will have something to look at.

**Comment by es128** [comment]
Looks good, but ultimately I was just looking for a simple yes/no on whether I can just replace the main minimatch function with the main micromatch one. Appears to be yes (assuming you don't expect input to always be an array). If I were you I'd call that out at the top of your README - that you can easily swap out either minimatch() or multimatch() for micromatch()

I'm interested in using it in anymatch btw, but want to be careful to not break any of its' users' existing patterns or use cases.

**Comment by jonschlinkert** [comment]
> I'm interested in using it in anymatch btw, but want to be careful to not break any of its' users' existing patterns or use cases.

That's great! I guess that's why I didn't put a simple yes/no lol. I want you to have the info you need to decide for yourself. But IMO the main difference is that the main `minimatch()` function returns true/false on a single file path, but the main `micromatch()` function works like multimatch. 

If you do use micromatch and have any issues, let me know right away and I'll get it fixed.

**Comment by es128** [comment]
Ah ok now I see.. you _can_ pass a single string to `micromatch()` but the return value will be an array instead of a boolean. I hadn't been familiar with `multimatch`'s API, so this distinction didn't click for me until I just went and tried it. Up to this point I was thinking I didn't really _need_ to specify the `isMatch` method and it would still work out. I know you already said it, just describing my thought process to hopefully help get the description tailored for easier consumption by the next person that comes around with a similar mindset.

So the TL;DR for what I wanted to find out at a glance is that you would replace

```js
minimatch(path, glob)
```

with

```js
micromatch.isMatch(path, glob)
```

**Comment by jonschlinkert** [comment]
exactly, thanks for helping me get that clear in my own head lol.

**Comment by jonschlinkert** [comment]
@es128 I just fixed a bug in micromatch that caused one of the tests to fail in anymatch. all tests pass now.

**Comment by es128** [comment]
Cool, thanks. I'll give it a try.

**Comment by jonschlinkert** [comment]
:+1:

**Comment by es128** [comment]
Closing as this has been addressed.

@jonschlinkert feel free to reopen if you felt there was anything left to be done with this.
