### ISSUE TITLE
[:punct:] expanded incorrectly

### ISSUE THREAD

**Issue by MartinKolarik** [jonschlinkert/micromatch#60]
`[:punct:]` is changed to ``[!"#$%&\'()\\*+,-./:;<=>?@[\\]^_`{|}~]`` [here](https://github.com/jonschlinkert/micromatch/blob/17f06276a9a1fc8858582612d73aec5abf8744c6/lib/expand.js#L117) and because it starts with `[!` it's changed to the negated version [right after](https://github.com/jonschlinkert/micromatch/blob/17f06276a9a1fc8858582612d73aec5abf8744c6/lib/expand.js#L122). I suppose the most simple fix would be changing order of the characters in the regex class.

**Comment by jonschlinkert** [comment]
want to do a pr?

**Comment by jonschlinkert** [comment]
actually this issue would belong on [expand-brackets](https://github.com/jonschlinkert/expand-brackets)

**Comment by MartinKolarik** [comment]
>actually this issue would belong on expand-brackets

Yeah, if we want to just swap the order, then yes. But technically speaking, it's an issue with micromatch, the pattern generated by expand-brackets is correct.

**Comment by MartinKolarik** [comment]
>the pattern generated by expand-brackets is correct

Actually, I take that back. This isn't the only problem with that pattern. Will submit a PR at https://github.com/jonschlinkert/expand-brackets
