### ISSUE TITLE
bug when absolute path and dot option true/false 

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/micromatch#62]
```js
var path = require('path')
var absolute = true

var filepath = absolute ? path.resolve('.git') : '.git'
var pattern = absolute ? path.resolve('**') : '**'

console.log(filepath)
console.log(pattern)

var matches = mm(filepath, pattern, {dot: false})
var ismatch = mm.isMatch(filepath, pattern, {dot: false})
var reEnabled = mm.makeRe(filepath, {dot: true})
var reDisabled = mm.makeRe(filepath, {dot: false})

console.log(matches) // => [ '/home/charlike/dev/final/glob-fs/.git' ]
console.log(ismatch) // => true
console.log(reEnabled.test(filepath)) // => true
console.log(reDisabled.test(filepath)) // => true
console.log(reEnabled)  // => /^(?:\/home\/charlike\/dev\/final\/glob-fs\/\.git)$/
console.log(reDisabled) // => /^(?:\/home\/charlike\/dev\/final\/glob-fs\/\.git)$/
```

Try out to change `absolute` to false and you get empty array. Which is the correct behaving when `dot: false`. But when absolute path and absolute pattern is passed it find match when `dot: false`.

**Comment by tunnckoCore** [comment]
Actually, looking the tests.. they also looks wrong?

```js
 mm.makeRe('.gitignore', {dot: true}).test('.gitignore').should.be.true;
 mm.makeRe('.gitignore', {dot: false}).test('.gitignore').should.be.true;
 mm.makeRe('.gitignore').test('.gitignore').should.be.true;
```

**Comment by MartinKolarik** [comment]
Those tests are correct. It should match dotfiles even with `dot: false` when dot is explicitly part of the pattern. `dot: true/false` only affects wildcards.

**Comment by tunnckoCore** [comment]
> It should match dotfiles even

I don't think so. That's the idea of that option for me.

Nevermind, issue is for other bug.

**Comment by tunnckoCore** [comment]
@jonschlinkert the whole point of this issue is because if we have directory with 1 file and 1 directory, and we want to pass `foobar/**` pattern it will return only the 1 file and 1 directory without the `foobar/` and this make sense because it comes as `foobar` and pattern want at least `foobar/`, so the trailing slash is problem. So i'm forced to add trailing slash before pass to micromatch.

Doesn't make sense `foobar/**` to match `foobar` and `foobar/`, exactly because `*` is zero or more?

**Comment by jonschlinkert** [comment]
> It should match dotfiles even with dot: false when dot is explicitly part of the pattern.

correct. the bash specification says that when `/.` is part of your pattern, it will always match dotfiles, even if `options.dot` is false.

**Comment by tunnckoCore** [comment]
> correct.

Okey, got it. But issue is a bit another, see my last post. And see this example it may clear it a bit

```js
function matchPlugin (patterns, options) {
  var matcher = require('is-match')
  var isMatch = matcher(patterns, options)

  return function matchPlugin (app) {
    return function (file) {
      var fp = file.path

      // this little hack is needed, for example:
      // pattern: foo/bar/**
      // -> foo/bar/baz
      // -> foo/bar/baz/qux.js
      // -> foo/bar/
      // -> foo/bar -> fails, so we tweak it with this hack
      if (file.stat.isDirectory()) {
        fp = file.path.charAt(-1) === '/' ? file.path.slice(0, -1) : file.path
        fp = fp + '/'
      }
      if (!file.exclude && !isMatch(fp)) file.exclude = true
    }
  }
}
```

**Comment by jonschlinkert** [comment]
Did you notice you're using `.makeRe` on the filepath, not on the pattern?

> is the refactor is near to push to github? :)

maybe, I'll look.

**Comment by MartinKolarik** [comment]
@jonschlinkert from @tunnckoCore's first post, it seems there actually is a bug:

```js
mm.isMatch('/aaa/bbb/.git', '/aaa/bbb/**'); // => true; should be false
```

**Comment by jonschlinkert** [comment]
yeah that's what I was thinking as well. but I hadn't had a chance to check. Is it only when the path is absolute?

**Comment by MartinKolarik** [comment]
>Is it only when the path is absolute?

No, it's the same for relative paths as well. But it's only an issue when a dotfile is at the same level as `**` - if it's inside a directory, it works correctly:

```js
mm.isMatch('/aaa/bbb/ccc/.git', '/aaa/bbb/**'); // => false; correct
```

**Comment by tunnckoCore** [comment]
@MartinKolarik yea, but that's another bug, maybe we should separate them in separate issues.

I'm talking for another.

```js
var micromatch = require('micromatch')
var isMatch = micromatch.matcher('foo/bar/**')
console.log(isMatch('foo/bar')) // => false
console.log(isMatch('foo/bar/')) // => true
console.log(isMatch('foo/bar/baz')) // => true
console.log(isMatch('foo/bar/baz/fez')) // => true
console.log(isMatch('foo/bar/baz/qux.js')) // => true
```

> Is it only when the path is absolute?

Hmm, I thought answer was `yes`, but huh.

```js

var micromatch = require('micromatch')
console.log(micromatch.isMatch('/aaa/bbb/.git', '/aaa/bbb/**', {dot: true}))
console.log(micromatch.isMatch('/aaa/bbb/.git', '/aaa/bbb/**', {dot: false}))
console.log(micromatch.isMatch('aaa/bbb/.git', 'aaa/bbb/**', {dot: true}))
console.log(micromatch.isMatch('aaa/bbb/.git', 'aaa/bbb/**', {dot: false}))
```
obviously, no.

**Comment by jonschlinkert** [comment]
> maybe we should separate them in separate issues.

let's do that please. Also try to just use the minimum reduced use case to illustrate the bug.  thanks

**Comment by MartinKolarik** [comment]
>@MartinKolarik yea, but that's another bug, maybe we should separate them in separate issues.

I see. From your original post, I thought this was the problem you were reporting :smile: 

>console.log(isMatch('foo/bar')) // => false, i think it make sense to pass?

I that case, `bar` might be a file in `foo` directory, and definitely shouldn't match.

**Comment by jonschlinkert** [comment]
closing this issue since we're splitting out
