### ISSUE TITLE
globstar and trailing slash

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/micromatch#64]
From #62 

```js
var micromatch = require('micromatch')
var isMatch = micromatch.matcher('foo/bar/**')
console.log(isMatch('foo/bar')) // => false, i think it make sense to pass?
console.log(isMatch('foo/bar/')) // => true
console.log(isMatch('foo/bar/baz')) // => true
console.log(isMatch('foo/bar/baz/fez')) // => true
console.log(isMatch('foo/bar/baz/qux.js')) // => true
```

If that's correct behaving, okey, but you are forced to do some hacks like https://github.com/jonschlinkert/micromatch/issues/62#issuecomment-213600188 and it not make sense for me.

edit: and `**` means anything or empty - same as single `*`. so basically if it make sense to match with trailing slash it make sense to match without it, because it is absolutely the same - in anyway it is the dir.

**Comment by MartinKolarik** [comment]
>because it is absolutely the same - in anyway it is the dir.

That's the problem here. Without the slash, there's no way to know if it's a dir or a file.

**Comment by jonschlinkert** [comment]
> If that's correct behaving, okey,

yeah it's correct. Try doing this:

```js
var micromatch = require('micromatch')
var isMatch = micromatch.matcher('foo/bar{,/**}')
console.log(isMatch('foo/bar')) // => true
```

**Comment by tunnckoCore** [comment]
Mm, yea, thanks.
