### ISSUE TITLE
Whitespace in path

### ISSUE THREAD

**Issue by electerious** [jonschlinkert/micromatch#66]
Hi, I'm trying to match files using the following pattern:

```js
require('micromatch')('/Users/tobiasreich/Sites/aaa/bbb/ccc 2016/src/de.ejs', [
	'/Users/tobiasreich/Sites/aaa/bbb/ccc 2016/src/**/[^_]*.{html,ejs}'
]) // => []
```

micromatch sadly returns an empty array, which is not what I expected. After several experiments I figured out that the whitespace between "ccc" and "2016" might be the reason for it.

```js
require('micromatch')('/Users/tobiasreich/Sites/aaa/bbb/ccc2016/src/de.ejs', [
	'/Users/tobiasreich/Sites/aaa/bbb/ccc2016/src/**/[^_]*.{html,ejs}'
]) // => ['/Users/tobiasreich/Sites/aaa/bbb/ccc2016/src/de.ejs']
```

Is this a problem of the pattern I'm using or an issue of micromatch? How should I deal with spaces in paths?

Node.js Version: 6.2
micromatch Version: 2.3.8

**Comment by jonschlinkert** [comment]
> Is this a problem of the pattern I'm using or an issue of micromatch? How should I deal with spaces in paths?

If it's failing on a space, that would be a bug. I'm guessing it's not just the space but a combination of the space and something else... I'll take a look, thanks for creating the issue

**Comment by jonschlinkert** [comment]
Yeah it's the brace pattern. For some reason it appears to be recognizing the whitespace as a boundary or a delimiter. I know where the problem is, I should be able to get a fix pushed up.

**Comment by jonschlinkert** [comment]
k, found it, and fixed it. I need to run some tests on braces and micromatch then I can push up

**Comment by jonschlinkert** [comment]
please reopen if you have any more issues, thanks!

**Comment by electerious** [comment]
That was fast. Thanks a lot for the quick fix!

**Comment by jonschlinkert** [comment]
Any time. I always appreciate getting issues for bugs. We all get busy and it's hard to take a few min and do that sometimes, but this lib is better as a result, so thank you!
