### ISSUE TITLE
how to get the contains matched string

### ISSUE THREAD

**Issue by SaitoWu** [jonschlinkert/micromatch#68]
The current `contains` method just returns true or false, is there anyway to get the contains string.

For example:

```javascript
// Old style
mm.contains('a/b/c', 'a/*');
//=> true

// New Style
mm.contains('a/b/c', 'a/*');
//=> a/b
```

In my case, I just want to `replace` the matched string with empty

**Comment by jonschlinkert** [comment]
Hmm, you could try using `.makeRe`, then manually edit the regex to add a capture group. Would that work for you?

**Comment by SaitoWu** [comment]
Yes, It worked, i was use it to solve the question.

But its not very convenient for me, and i must do a lot of work for the regex.

I must remove the `$` at the end of the `makeRe` created, and do some other works if a have some regex modifications.

What i really need is:

```javascript
'abc'.replace(mm.contains('a/b/c', 'a/*'), '')
// => c
```

Or maybe the more comfortable one:

```javascript
mm.notContains('a/b/c', 'a/*')
// => c
```

I'm very glad to see the library can have this function.

Thanks. 

Have a good day! 

🍻🍻🍻

**Comment by jonschlinkert** [comment]
> I must remove the $ at the end of the makeRe created

You [should be able](https://github.com/jonschlinkert/micromatch/blob/master/index.js#L366-L367) to do this:

``js
var re = mm.makeRe('a/*', {contains: true});
```

Would something like this work for you?

```js

function getMatch(filepath, pattern) {
  var regex = mm.makeRe(pattern, {contains: true});
  var re = new RegExp('(' + re.source + ')');
  var match = re.exec(filepath);
  // do something with `match`...
}
```

**Comment by SaitoWu** [comment]
Wow, `{contains: true}` really make sense.

Thanks for your advise!

🎊🎊🎊

**Comment by jonschlinkert** [comment]
My pleasure, glad I could help.
