### ISSUE TITLE
possibility `.filter` to accept array glob pattern

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/micromatch#7]
Like...

```js
[
  'fs-readdir-callback-api.js',
  'fs-readdir-stream-api.js',
  'glob-stream.js',
  'readdirp-callback-api.js',
  'readdirp-stream-api.js',
  'recursive-readdir.js'
].filter(micromatch.filter(['*', '!*api*']))
//=> ['glob-stream.js', 'recursive-readdir.js']
```

**Use case if `.filter` accepts array**
this [part of recursive-readdir](https://github.com/jergason/recursive-readdir/blob/master/index.js#L24-L34) package would become something like this

```js
var ignoreOpts = {dot: true, matchBase: true};
var nonIgnores = ignores.filter(function(ignore) {
  return ignore.chatAt(0) !== '!';
})
var ignored = map(nonIgnores, function(ignore) {
  return '!' + ignore;
});
ignores = [].concat([ignores, ignored])
var ignoreFilter = micromatch.filter(ignores, ignoreOpts)

files.filter(ignoreFilter).forEach(function (file) {
  // ... another code below
```

**Comment by jonschlinkert** [comment]
sorry don't know how I missed this!.

Maybe I'm missing something, but why is any of that needed? Couldn't this be achieved by using the main function instead of filter?

```js
micromatch(files, ['*', '!*api*']);
```

If additional `ignore` patterns need to be passed, you can do: 

```js
micromatch(files, ['*', '!*api*'], {ignore: ['foo/*', '**/bar']);
```

**Comment by tunnckoCore** [comment]
Hmmm. Maybe, I'll review it soon, I think I got it.

Actually, it's not an issue, cuz [`fs-readdir`](https://github.com/tunnckoCore/fs-readdir) is almost the fastest async/stream out there. ASAP I'll add support for globs and filters using micromatch. :)

Cute avatar btw! :+1:

**Comment by tunnckoCore** [comment]
btw why when benchmark ends not close the std? I mean.. I need to CTRL + C to exit from benchmark.

Can you review benchmarked config, is I missing something?

**Comment by jonschlinkert** [comment]
> I need to CTRL + C to exit from benchmark.

really? hmm, honestly I created benchmarked in like 30 min lol. I just needed something fast, but I should revisit since I use it so much. 

> Maybe, I'll review it soon, I think I got it.

Actually I might be wrong. It depends... I was thinking about it, maybe it would make the most sense if either a) `.isMatch()` could take an array of patterns, since that could be used for filtering, or b) we just add multi-pattern functionality like you said... I'll think about it, let me know if you have more suggestions

**Comment by tunnckoCore** [comment]
> really? hmm, honestly I created benchmarked in like 30 min lol. I just needed something fast, but I should revisit since I use it so much.

Yep. idk, but always, maybe I'm in some mistake when implement it, lol.

> I'll think about it, let me know if you have more suggestions

Agreed. Both are good ideas.

**Comment by jonschlinkert** [comment]
> maybe I'm in some mistake when implement it, lol.

that looks right to me. I think there is a bug.

**Comment by tunnckoCore** [comment]
Isn't bug label for benchmarked, not here? lol

**Comment by jonschlinkert** [comment]
lol, that's the problem with off-topic conversations.

**Comment by jonschlinkert** [comment]
and thanks, I get a little absentminded when I'm working on something.

**Comment by tunnckoCore** [comment]
> want to create an issue over there?

yep yep, no problem, lol, i'll soon

**Comment by jonschlinkert** [comment]
ok I think I got it. Instead of `.filter()` how about `.every()`?

**Comment by jonschlinkert** [comment]
e.g. "every pattern", not files
