### ISSUE TITLE
Update is-glob

### ISSUE THREAD

**Issue by phated** [jonschlinkert/micromatch#72]
I just updated my `glob-parent` dependency in `glob-stream` and was warned about micromatch requiring a different version.  Thought I'd give the heads up.

**Comment by jonschlinkert** [comment]
thanks, I just worked on a refactor for the past few days. `glob-parent` probably won't be needed in the next version.

**Comment by jonschlinkert** [comment]
closing in light of the [refactor](https://github.com/jonschlinkert/micromatch/pull/76)
