### ISSUE TITLE
/foo/ doesn't match *f*

### ISSUE THREAD

**Issue by laggingreflex** [jonschlinkert/micromatch#74]
mm.isMatch('foo', 'f*');
    //=> true [ok]

    mm.isMatch('/foo/', '*f*');
    //=> false [?]

Is this intentional?

**Comment by jonschlinkert** [comment]
> Is this intentional?

Yes, a single `*` never matches slashes. This follows bash spec, so if you look for `bash glob`, `bash globbing`, `globstar` etc on google you'll find a lot of good info on using wildcards and rules for using them. The unit tests are also a good resource.
