### ISSUE TITLE
Notes on differences between bash 4.3.33, dash 0.5.7, and micromatch 2.3.11

### ISSUE THREAD

**Issue by jepler** [jonschlinkert/micromatch#75]
I tested bash with `shopt -s nullglob extglobs`.

~~~~
                            # micromatch        bash        dash
                            # 2.3.11            4.3.33(1)   0.5.7-4+b1
mm(['a-b'], 'a[]-]b')       # none              a-b         a-b
~~~~
`[]-]` matches `]` or `-`.
~~~~
mm(['1', '5'], '[!-5]')     # none              1           1
~~~~
`[!-5]` matches anything but `-` or `5`.

~~~~
mm(['a/b'], 'a[/]b')        # a/b               none        a[/]b
mm(['a/b'], '*([ab/])')     # a/b               none        [ab/]
~~~~
`[/]` and `[ab/]` are not sets of characters.  Dash doesn't support nullglob, so an unmatched pattern is itself.  (Furthermore, the second example is an extglob, which dash doesn't support.)

~~~~
mm(['a/b', 'a.b'], 'a[.-0]b') # a/b a.b         a.b
~~~~
`[.-0]` is a set of characters, but not one which matches `/` (even though the ASCII value of `/` is between `.` and `0`)

**Comment by jonschlinkert** [comment]
what is dash? and what is the point of this issue? Also, anything we discuss here is irrelevant after I push up the latest changes from extglob, nanomatch and braces. Each of which are more accurate than bash and follow specifications exactly.

**Comment by jepler** [comment]
Yes, that dash.  I'm glad you found at least one of my test cases useful to add.

**Comment by jonschlinkert** [comment]
That test is from git wildmatch and was already included in the nanomatch tests: https://github.com/jonschlinkert/nanomatch/blob/master/test/bash.js#L97-L108. 

Other similar tests: https://github.com/jonschlinkert/nanomatch/blob/master/test/bash.js#L125-L138
