### ISSUE TITLE
Incorrect matching when path contains braces 

### ISSUE THREAD

**Issue by electerious** [jonschlinkert/micromatch#77]
Hi, I'm trying to match a path that contains braces.

```js
require('micromatch').any('/frontend(w)/src/news.ejs', ['/frontend(w)/src/[^_]*.{html,ejs}*']) // false
```

The given command returns `false`, but I expected `true`. Removing the braces from the path fixes the problem, escaping doesn't:

```js
require('micromatch').any('/frontend/src/news.ejs', ['/frontend/src/[^_]*.{html,ejs}*']) // true
```

```js
require('micromatch').any('/frontend\(w\)/src/news.ejs', ['/frontend\(w\)/src/[^_]*.{html,ejs}*']) // false
```

Node.js Version: 6.2
micromatch Version: 2.3.11

**Comment by doowb** [comment]
@electerious only the `( )` in the glob pattern need to be escaped, but you also need to escape the escape character since it's being used in a string (this just means double backslash like this:

```js
require('micromatch').any('/frontend(w)/src/news.ejs', ['/frontend\\(w\\)/src/[^_]*.{html,ejs}*'])
```

**Comment by electerious** [comment]
Ah, you're right. Thanks!

The glob-pattern is auto-generated. The first part is the current path. Are you aware of a smart way to escape a path to a glob-friendly string. Or with other words: A way to escape all chars that are special in glob-patterns?
