### ISSUE TITLE
Single character in combination with a dot (.) results in no matches

### ISSUE THREAD

**Issue by asgoth** [jonschlinkert/micromatch#78]
If I try the following combinations, it results in no matches (failing tests):
      
     mm(['a/bbb/abcd.md'], ['a/bbb/ab??.md']).should.eql(['a/bbb/abcd.md']);
     mm(['a/bbb/abcd.md'], ['a/*/ab??.md']).should.eql(['a/bbb/abcd.md']);

Only when removing the dot (.) from the pattern, makes it succeed:

    mm(['a/bbb/abcd.md'], ['a/bbb/ab???md']).should.eql(['a/bbb/abcd.md']);

Is this expected behaviour?

**Comment by jonschlinkert** [comment]
Thanks for the issue. There is a [refactor](https://github.com/jonschlinkert/micromatch/pull/76) that will be published in the next few days with this fix.
