### ISSUE TITLE
need help creating windows patterns

### ISSUE THREAD

**Issue by HrOice** [jonschlinkert/micromatch#84]
The path on windows contains "\\",but cause bugs: 
```
mm.makeRe("C:\\Users\\pro\\Desktop\\entei\\app\\{components_vendor,components}\\**\\images\\other-images\\")
/^(?:C:UsersproDesktopenteiapp{components_vendor,components}(?!\.)(?=.)[^\/]*?(?!(?:\/|^)\.{1,2}($|\/))(?=.)[^\/]*?imagesother-images)$/
```

can you help me ?
I find the final code:
micromatch-master/node_modules/braces/index.js:escapeBraces  
```
 return arr.concat(str.split('\\').join(''));
```

**Comment by jonschlinkert** [comment]
You will need to use forward slashes in globs, even on windows. 

Backslashes are reserved for escaping in glob patterns, and windows supports forward slashes as path separators. 

fwiw, none of the globbing libs allow backslashes as path separators in globs (including bash, [minimatch and node-glob](https://github.com/isaacs/node-glob#windows)).

**Comment by HrOice** [comment]
Thank you, I see! ^ ^

**Comment by jonschlinkert** [comment]
great, I'll go ahead and close. Feel free to ask more questions
