### ISSUE TITLE
Trouble using this module

### ISSUE THREAD

**Issue by jamen** [jonschlinkert/micromatch#86]
Hello @jonschlinkert, I am trying to create something with this module that streams files with `files.read(globs)`, but I am having trouble using `mm.any` to check each path in the pipeline

I have isolated the problem to this for simplicity:

```js
mm.any('foo.js', ['foo.js'])
// true
mm.any('foo.js', ['*.js', '!foo.js'])
// true
```
How does this yield `true` if I'm explicitly negating it?  Is there a function that lets me do this type of check?

**Comment by jamen** [comment]
I think I am misunderstanding the purpose of `mm.any`.  Does it support negation?

Is there a way I can check a single path against multiple globs?  I tried the other methods but they didn't seem to do what I want.

**Comment by jamen** [comment]
I also tried using `mm.filter`, but I was getting a different problem:

```js
mm.filter(['foo/*.js', '!foo/qux.js'])('foo/bar.js')
// true.  this is fine
mm.filter(['foo/*.js', '!foo/qux.js', 'bar/test.js'])('foo/bar.js')
// false. the new base directory makes the previous one fail
```

**Comment by jamen** [comment]
I guess basically `mm.isMatch()` except could take an array of globs.

**Comment by jamen** [comment]
I was able to do it using `globs.some(x => isMatch(path, x))`

Nevermind :smile:

**Comment by doowb** [comment]
You can do something like this:

```js
function matches(path) {
  return mm(path, globs).length !== 0;
}
```

That will account for the negations. `mm.any` will return `true` if any of the glob patterns match the file path, meaning that it works like an `or`.

**Comment by jonschlinkert** [comment]
> How does this yield true if I'm explicitly negating it? Is there a function that lets me do this type of check?

The description from the readme is "Returns true if a file path matches any of the given patterns". The file path matches the inclusive pattern, so it returns true. 

You can simplify your logic a big by doing something like this:

```js
console.log(mm(['foo.js'], ['*.js', '!foo.js']).length > 0);
// false
```
But I can see the need for a method that does something similar to `.any` but with paths instead of patterns. 

Maybe `.some`? I just did a quick implementation that yields:

```js
console.log(mm.some(['foo.js', 'bar.js'], ['*.js', '!foo.js']));
// true

console.log(mm.some(['foo.js'], ['*.js', '!foo.js']));
// false
```

**Comment by jamen** [comment]
I did consider the `.length` way but I want to make it to where I don't have to create it for each file in the pipeline.

Also, with `.some`, I don't think that is what I would expect either.

I am basically receiving singular paths inside the pipeline, so I would never end up with something like `[ 'foo.js', 'bar.js' ]`.

For me it's more like I'm just checking if the path is negated anywhere inside the globs.  I don't care if the path matches against the other non-negation patterns , like `bar.js !== foo.js` in the pattern makes it return `false` when I don't care to match that...

Kind of hard to sum it up.  But an example of using the function might be:

```js
files.read([ 'foo/**/*.js', 'bar/**/*.js', '!**/qux.js' ])
```

This would make no globs match, because you have two different bases `foo` and `bar` that makes everything fail.

**Comment by jonschlinkert** [comment]
> I did consider the .length way but I want to make it to where I don't have to create mutiple arrays for each file in the pipeline

It depends on how big the list is (of paths, not patterns). Sometimes a breadth-first search like this is orders of magnitude faster when the function exits early on positive or negative matches (especially given that the patterns and matcher functions are memoized).

**Comment by jamen** [comment]
Well, what I am doing is admittedly kind of confusing.

Instead of collecting multiple paths and filtering them based on some patterns, I am recursively reading directories using a stream, and filtering it path-by-path.

So if I got `files.read([ 'foo/**.js', 'bar/**.js' ])`, it would start reading both `foo/` and `bar/` directories recursively, but also use negations to avoid some unnecessary reads...  Instead of reading everything and then filtering them.

**Comment by jonschlinkert** [comment]
> So if I got files.read([ 'foo/**.js', 'bar/**.js' ]), it would start reading both foo/ and bar/ directories recursively, but also use negations to avoid some unnecessary reads... Instead of reading everything and then filtering them.

we were just talking about this. I'm re-factoring glob-fs and we're thinking about similar challenges there.

**Comment by jamen** [comment]
@jonschlinkert Ended up making that in case you were curious: [`pull-files`](https://github.com/jamen/pull-files).  It turned out pretty great, but I still have some bigger optimizations in the back of my mind I am not willing to take on right now.  Still does reads x4+ faster than [`vinyl-fs`](https://github.com/gulpjs/vinyl-fs) on my machine, not counting the reduced complexity pull-streams would provide for file transforms and writes, but it is worth benchmarking those too.

**Comment by jonschlinkert** [comment]
that's great! nice work.
